export function conjugate(root, pattern) {
    const ar1 = root.ar[0];
    const ar2 = root.ar[1];
    const ar3 = root.ar[2];
    const en1 = root.en[0];
    const en2 = root.en[1];
    const en3 = root.en[2];

    if (pattern.form === "1") {
        if (pattern.pattern === 'A1') {
            return {
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}${en2}i${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `mni${en1}${en2}i${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bti${en1}${en2}i${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bti${en1}${en2}i${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bi${en1}${en2}i${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `bti${en1}${en2}i${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}${en2}i${en3}u`,
                past1S: `${ar1}${ar2}${ar3}ت`,
                past1Str: `${en1}a${en2}a${en3}t`,
                past1P: `${ar1}${ar2}${ar3}نا`,
                past1Ptr: `${en1}a${en2}a${en3}na`,
                past2F: `${ar1}${ar2}${ar3}تي`,
                past2Ftr: `${en1}a${en2}a${en3}ti`,
                past2P: `${ar1}${ar2}${ar3}تو`,
                past2Ptr: `${en1}a${en2}a${en3}tu`,
                past3M: `${ar1}${ar2}${ar3}`,
                past3Mtr: `${en1}a${en2}a${en3}`,
                past3F: `${ar1}${ar2}${ar3}ت`,
                past3Ftr: `${en1}a${en2}${en3}at`,
                past3P: `${ar1}${ar2}${ar3}و`,
                past3Ptr: `${en1}a${en2}a${en3}u`,
                amr2M: `إ${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔi${en1}${en2}i${en3}`,
                amr2F: `إ${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔi${en1}${en2}i${en3}i`,
                amr2P: `إ${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔi${en1}${en2}i${en3}u`,
            };

        } else {
            return {
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}${en2}i${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `mni${en1}${en2}i${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bti${en1}${en2}i${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bti${en1}${en2}i${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bi${en1}${en2}i${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `bti${en1}${en2}i${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}${en2}i${en3}u`,
                past1S: `${ar1}${ar2}${ar3}ت`,
                past1Str: `${en1}a${en2}a${en3}t`,
                past1P: `${ar1}${ar2}${ar3}نا`,
                past1Ptr: `${en1}a${en2}a${en3}na`,
                past2F: `${ar1}${ar2}${ar3}تي`,
                past2Ftr: `${en1}a${en2}a${en3}ti`,
                past2P: `${ar1}${ar2}${ar3}تو`,
                past2Ptr: `${en1}a${en2}a${en3}tu`,
                past3M: `${ar1}${ar2}${ar3}`,
                past3Mtr: `${en1}a${en2}a${en3}`,
                past3F: `${ar1}${ar2}${ar3}ت`,
                past3Ftr: `${en1}a${en2}${en3}at`,
                past3P: `${ar1}${ar2}${ar3}و`,
                past3Ptr: `${en1}a${en2}a${en3}u`,
                amr2M: `إ${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔi${en1}${en2}i${en3}`,
                amr2F: `إ${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔi${en1}${en2}i${en3}i`,
                amr2P: `إ${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔi${en1}${en2}i${en3}u`,
            };
        }

    } else {
        return {
            imp1S: `ب${ar1}${ar2}${ar3}`,
            imp1Str: `ba${en1}${en2}i${en3}`,
            imp1P: `من${ar1}${ar2}${ar3}`,
            imp1Ptr: `mni${en1}${en2}i${en3}`,
            imp2F: `بت${ar1}${ar2}${ar3}ي`,
            imp2Ftr: `bti${en1}${en2}i${en3}i`,
            imp2P: `بت${ar1}${ar2}${ar3}و`,
            imp2Ptr: `bti${en1}${en2}i${en3}u`,
            imp3M: `ب${ar1}${ar2}${ar3}`,
            imp3Mtr: `bi${en1}${en2}i${en3}`,
            imp3F: `بت${ar1}${ar2}${ar3}`,
            imp3Ftr: `bti${en1}${en2}i${en3}`,
            imp3P: `ب${ar1}${ar2}${ar3}و`,
            imp3Ptr: `bi${en1}${en2}i${en3}u`,
            past1S: `${ar1}${ar2}${ar3}ت`,
            past1Str: `${en1}a${en2}a${en3}t`,
            past1P: `${ar1}${ar2}${ar3}نا`,
            past1Ptr: `${en1}a${en2}a${en3}na`,
            past2F: `${ar1}${ar2}${ar3}تي`,
            past2Ftr: `${en1}a${en2}a${en3}ti`,
            past2P: `${ar1}${ar2}${ar3}تو`,
            past2Ptr: `${en1}a${en2}a${en3}tu`,
            past3M: `${ar1}${ar2}${ar3}`,
            past3Mtr: `${en1}a${en2}a${en3}`,
            past3F: `${ar1}${ar2}${ar3}ت`,
            past3Ftr: `${en1}a${en2}${en3}at`,
            past3P: `${ar1}${ar2}${ar3}و`,
            past3Ptr: `${en1}a${en2}a${en3}u`,
            amr2M: `إ${ar1}${ar2}${ar3}`,
            amr2Mtr: `ʔi${en1}${en2}i${en3}`,
            amr2F: `إ${ar1}${ar2}${ar3}ي`,
            amr2Ftr: `ʔi${en1}${en2}i${en3}i`,
            amr2P: `إ${ar1}${ar2}${ar3}و`,
            amr2Ptr: `ʔi${en1}${en2}i${en3}u`,
        };
    }
}
