export function conjugate(root, pattern) {
    const ar1 = root.ar[0];
    const ar2 = root.ar[1];
    const ar3 = root.ar[2];
    const ar4 = root.ar[3];
    const en1 = root.en[0];
    const en2 = root.en[1];
    const en3 = root.en[2];
    const en4 = root.en[3];

    const forms = {
        "1": {
            "A1": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}${en2}i${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `mni${en1}${en2}i${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bti${en1}${en2}i${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bti${en1}${en2}i${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bi${en1}${en2}i${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `bti${en1}${en2}i${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}${en2}i${en3}u`,
                past1S: `${ar1}${ar2}${ar3}ت`,
                past1Str: `${en1}a${en2}a${en3}t`,
                past1P: `${ar1}${ar2}${ar3}نا`,
                past1Ptr: `${en1}a${en2}a${en3}na`,
                past2F: `${ar1}${ar2}${ar3}تي`,
                past2Ftr: `${en1}a${en2}a${en3}ti`,
                past2P: `${ar1}${ar2}${ar3}تو`,
                past2Ptr: `${en1}a${en2}a${en3}tu`,
                past3M: `${ar1}${ar2}${ar3}`,
                past3Mtr: `${en1}a${en2}a${en3}`,
                past3F: `${ar1}${ar2}${ar3}ت`,
                past3Ftr: `${en1}a${en2}${en3}at`,
                past3P: `${ar1}${ar2}${ar3}و`,
                past3Ptr: `${en1}a${en2}a${en3}u`,
                amr2M: `إ${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔi${en1}${en2}i${en3}`,
                amr2F: `إ${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔi${en1}${en2}i${en3}i`,
                amr2P: `إ${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔi${en1}${en2}i${en3}u`,
            }),

            "A1a": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}${en2}a${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `mni${en1}${en2}a${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bti${en1}${en2}a${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bti${en1}${en2}a${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bi${en1}${en2}a${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `bti${en1}${en2}a${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}${en2}a${en3}u`,
                past1S: `${ar1}${ar2}${ar3}ت`,
                past1Str: `${en1}a${en2}a${en3}t`,
                past1P: `${ar1}${ar2}${ar3}نا`,
                past1Ptr: `${en1}a${en2}a${en3}na`,
                past2F: `${ar1}${ar2}${ar3}تي`,
                past2Ftr: `${en1}a${en2}a${en3}ti`,
                past2P: `${ar1}${ar2}${ar3}تو`,
                past2Ptr: `${en1}a${en2}a${en3}tu`,
                past3M: `${ar1}${ar2}${ar3}`,
                past3Mtr: `${en1}a${en2}a${en3}`,
                past3F: `${ar1}${ar2}${ar3}ت`,
                past3Ftr: `${en1}a${en2}${en3}at`,
                past3P: `${ar1}${ar2}${ar3}و`,
                past3Ptr: `${en1}a${en2}a${en3}u`,
                amr2M: `إ${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔi${en1}${en2}a${en3}`,
                amr2F: `إ${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔi${en1}${en2}a${en3}i`,
                amr2P: `إ${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔi${en1}${en2}a${en3}u`,
            }),

            "A1u": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}${en2}u${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `mnu${en1}${en2}u${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `btu${en1}${en2}u${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `btu${en1}${en2}u${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bu${en1}${en2}u${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `btu${en1}${en2}u${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bu${en1}${en2}u${en3}u`,
                past1S: `${ar1}${ar2}${ar3}ت`,
                past1Str: `${en1}a${en2}a${en3}t`,
                past1P: `${ar1}${ar2}${ar3}نا`,
                past1Ptr: `${en1}a${en2}a${en3}na`,
                past2F: `${ar1}${ar2}${ar3}تي`,
                past2Ftr: `${en1}a${en2}a${en3}ti`,
                past2P: `${ar1}${ar2}${ar3}تو`,
                past2Ptr: `${en1}a${en2}a${en3}tu`,
                past3M: `${ar1}${ar2}${ar3}`,
                past3Mtr: `${en1}a${en2}a${en3}`,
                past3F: `${ar1}${ar2}${ar3}ت`,
                past3Ftr: `${en1}a${en2}${en3}at`,
                past3P: `${ar1}${ar2}${ar3}و`,
                past3Ptr: `${en1}a${en2}a${en3}u`,
                amr2M: `أ${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔu${en1}${en2}u${en3}`,
                amr2F: `أ${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔu${en1}${en2}u${en3}i`,
                amr2P: `أ${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔu${en1}${en2}u${en3}u`,
            }),

            "A1h": () => ({
                imp1S: `با${ar2}${ar3}`,
                imp1Str: `bā${en2}u${en3}`,
                imp1P: `منا${ar2}${ar3}`,
                imp1Ptr: `mnā${en2}u${en3}`,
                imp2F: `بتا${ar2}${ar3}ي`,
                imp2Ftr: `btā${en2}u${en3}i`,
                imp2P: `بتا${ar2}${ar3}و`,
                imp2Ptr: `btā${en2}u${en3}u`,
                imp3M: `با${ar2}${ar3}`,
                imp3Mtr: `bā${en2}u${en3}`,
                imp3F: `بتا${ar2}${ar3}`,
                imp3Ftr: `btā${en2}u${en3}`,
                imp3P: `با${ar2}${ar3}و`,
                imp3Ptr: `bā${en2}u${en3}u`,
                past1S: `${ar1}${ar2}${ar3}ت`,
                past1Str: `${en1}a${en2}a${en3}t`,
                past1P: `${ar1}${ar2}${ar3}نا`,
                past1Ptr: `${en1}a${en2}a${en3}na`,
                past2F: `${ar1}${ar2}${ar3}تي`,
                past2Ftr: `${en1}a${en2}a${en3}ti`,
                past2P: `${ar1}${ar2}${ar3}تو`,
                past2Ptr: `${en1}a${en2}a${en3}tu`,
                past3M: `${ar1}${ar2}${ar3}`,
                past3Mtr: `${en1}a${en2}a${en3}`,
                past3F: `${ar1}${ar2}${ar3}ت`,
                past3Ftr: `${en1}a${en2}${en3}at`,
                past3P: `${ar1}${ar2}${ar3}و`,
                past3Ptr: `${en1}a${en2}a${en3}u`,
                amr2M: `${ar2}${ar3}`,
                amr2Mtr: `${en2}u${en3}`,
                amr2F: `${ar2}${ar3}ي`,
                amr2Ftr: `${en2}u${en3}i`,
                amr2P: `${ar2}${ar3}و`,
                amr2Ptr: `${en2}u${en3}u`,
            }),

            "A2": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}${en2}a${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `mni${en1}${en2}a${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bti${en1}${en2}a${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bti${en1}${en2}a${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bi${en1}${en2}a${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `bti${en1}${en2}a${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}${en2}a${en3}u`,
                past1S: `${ar1}${ar2}${ar3}ت`,
                past1Str: `${en1}${en2}i${en3}t`,
                past1P: `${ar1}${ar2}${ar3}نا`,
                past1Ptr: `${en1}${en2}i${en3}na`,
                past2F: `${ar1}${ar2}${ar3}تي`,
                past2Ftr: `${en1}${en2}i${en3}ti`,
                past2P: `${ar1}${ar2}${ar3}تو`,
                past2Ptr: `${en1}${en2}i${en3}tu`,
                past3M: `${ar1}${ar2}${ar3}`,
                past3Mtr: `${en1}i${en2}i${en3}`,
                past3F: `${ar1}${ar2}${ar3}ت`,
                past3Ftr: `${en1}i${en2}${en3}at`,
                past3P: `${ar1}${ar2}${ar3}و`,
                past3Ptr: `${en1}i${en2}i${en3}u`,
                amr2M: `إ${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔi${en1}${en2}a${en3}`,
                amr2F: `إ${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔi${en1}${en2}a${en3}i`,
                amr2P: `إ${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔi${en1}${en2}a${en3}u`,
            }),

            "A2i": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}${en2}i${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `mni${en1}${en2}i${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bti${en1}${en2}i${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bti${en1}${en2}i${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bi${en1}${en2}i${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `bti${en1}${en2}i${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}${en2}i${en3}u`,
                past1S: `${ar1}${ar2}${ar3}ت`,
                past1Str: `${en1}${en2}i${en3}t`,
                past1P: `${ar1}${ar2}${ar3}نا`,
                past1Ptr: `${en1}${en2}i${en3}na`,
                past2F: `${ar1}${ar2}${ar3}تي`,
                past2Ftr: `${en1}${en2}i${en3}ti`,
                past2P: `${ar1}${ar2}${ar3}تو`,
                past2Ptr: `${en1}${en2}i${en3}tu`,
                past3M: `${ar1}${ar2}${ar3}`,
                past3Mtr: `${en1}i${en2}i${en3}`,
                past3F: `${ar1}${ar2}${ar3}ت`,
                past3Ftr: `${en1}i${en2}${en3}at`,
                past3P: `${ar1}${ar2}${ar3}و`,
                past3Ptr: `${en1}i${en2}i${en3}u`,
                amr2M: `إ${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔi${en1}${en2}a${en3}`,
                amr2F: `إ${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔi${en1}${en2}a${en3}i`,
                amr2P: `إ${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔi${en1}${en2}a${en3}u`,
            }),

            "B1": () => ({
                imp1S: `ب${ar1}${ar2}ي`,
                imp1Str: `ba${en1}${en2}i`,
                imp1P: `من${ar1}${ar2}ي`,
                imp1Ptr: `mni${en1}${en2}i`,
                imp2F: `بت${ar1}${ar2}ي`,
                imp2Ftr: `bti${en1}${en2}i`,
                imp2P: `بت${ar1}${ar2}و`,
                imp2Ptr: `bti${en1}${en2}u`,
                imp3M: `ب${ar1}${ar2}ي`,
                imp3Mtr: `bi${en1}${en2}i`,
                imp3F: `بت${ar1}${ar2}ي`,
                imp3Ftr: `bti${en1}${en2}i`,
                imp3P: `ب${ar1}${ar2}و`,
                imp3Ptr: `bi${en1}${en2}u`,
                past1S: `${ar1}${ar2}يت`,
                past1Str: `${en1}a${en2}ēt`,
                past1P: `${ar1}${ar2}ينا`,
                past1Ptr: `${en1}a${en2}ēna`,
                past2F: `${ar1}${ar2}يتي`,
                past2Ftr: `${en1}a${en2}ēti`,
                past2P: `${ar1}${ar2}يتو`,
                past2Ptr: `${en1}a${en2}ētu`,
                past3M: `${ar1}${ar2}ى`,
                past3Mtr: `${en1}a${en2}a`,
                past3F: `${ar1}${ar2}ت`,
                past3Ftr: `${en1}a${en2}at`,
                past3P: `${ar1}${ar2}و`,
                past3Ptr: `${en1}a${en2}u`,
                amr2M: `إ${ar1}${ar2}ي`,
                amr2Mtr: `ʔi${en1}${en2}i`,
                amr2F: `إ${ar1}${ar2}ي`,
                amr2Ftr: `ʔi${en1}${en2}i`,
                amr2P: `إ${ar1}${ar2}و`,
                amr2Ptr: `ʔi${en1}${en2}u`,
            }),

            "B1a": () => ({
                imp1S: `ب${ar1}${ar2}ا`,
                imp1Str: `ba${en1}${en2}a`,
                imp1P: `من${ar1}${ar2}ا`,
                imp1Ptr: `mni${en1}${en2}a`,
                imp2F: `بت${ar1}${ar2}ي`,
                imp2Ftr: `bti${en1}${en2}i`,
                imp2P: `بت${ar1}${ar2}و`,
                imp2Ptr: `bti${en1}${en2}u`,
                imp3M: `ب${ar1}${ar2}ا`,
                imp3Mtr: `bi${en1}${en2}a`,
                imp3F: `بت${ar1}${ar2}ا`,
                imp3Ftr: `bti${en1}${en2}a`,
                imp3P: `ب${ar1}${ar2}و`,
                imp3Ptr: `bi${en1}${en2}u`,
                past1S: `${ar1}${ar2}يت`,
                past1Str: `${en1}a${en2}ēt`,
                past1P: `${ar1}${ar2}ينا`,
                past1Ptr: `${en1}a${en2}ēna`,
                past2F: `${ar1}${ar2}يتي`,
                past2Ftr: `${en1}a${en2}ēti`,
                past2P: `${ar1}${ar2}يتو`,
                past2Ptr: `${en1}a${en2}ētu`,
                past3M: `${ar1}${ar2}ا`,
                past3Mtr: `${en1}a${en2}a`,
                past3F: `${ar1}${ar2}ت`,
                past3Ftr: `${en1}a${en2}at`,
                past3P: `${ar1}${ar2}و`,
                past3Ptr: `${en1}a${en2}u`,
                amr2M: `إ${ar1}${ar2}ا`,
                amr2Mtr: `ʔi${en1}${en2}a`,
                amr2F: `إ${ar1}${ar2}ي`,
                amr2Ftr: `ʔi${en1}${en2}i`,
                amr2P: `إ${ar1}${ar2}و`,
                amr2Ptr: `ʔi${en1}${en2}u`,
            }),

            "B2": () => ({
                imp1S: `ب${ar1}${ar2}ى`,
                imp1Str: `ba${en1}${en2}a`,
                imp1P: `من${ar1}${ar2}ى`,
                imp1Ptr: `mni${en1}${en2}a`,
                imp2F: `بت${ar1}${ar2}ي`,
                imp2Ftr: `bti${en1}${en2}i`,
                imp2P: `بت${ar1}${ar2}و`,
                imp2Ptr: `bti${en1}${en2}u`,
                imp3M: `ب${ar1}${ar2}ى`,
                imp3Mtr: `bi${en1}${en2}a`,
                imp3F: `بت${ar1}${ar2}ى`,
                imp3Ftr: `bti${en1}${en2}a`,
                imp3P: `ب${ar1}${ar2}و`,
                imp3Ptr: `bi${en1}${en2}u`,
                past1S: `${ar1}${ar2}يت`,
                past1Str: `${en1}${en2}īt`,
                past1P: `${ar1}${ar2}ينا`,
                past1Ptr: `${en1}${en2}īna`,
                past2F: `${ar1}${ar2}يتي`,
                past2Ftr: `${en1}${en2}īti`,
                past2P: `${ar1}${ar2}يتو`,
                past2Ptr: `${en1}${en2}ītu`,
                past3M: `${ar1}${ar2}ي`,
                past3Mtr: `${en1}i${en2}i`,
                past3F: `${ar1}${ar2}يت`,
                past3Ftr: `${en1}i${en2}yat`,
                past3P: `${ar1}${ar2}و`,
                past3Ptr: `${en1}i${en2}u`,
                amr2M: `إ${ar1}${ar2}ى`,
                amr2Mtr: `ʔi${en1}${en2}a`,
                amr2F: `إ${ar1}${ar2}ي`,
                amr2Ftr: `ʔi${en1}${en2}i`,
                amr2P: `إ${ar1}${ar2}و`,
                amr2Ptr: `ʔi${en1}${en2}u`,
            }),

            "B2i": () => ({
                imp1S: `ب${ar1}${ar2}ي`,
                imp1Str: `ba${en1}${en2}i`,
                imp1P: `من${ar1}${ar2}ي`,
                imp1Ptr: `mni${en1}${en2}i`,
                imp2F: `بت${ar1}${ar2}ي`,
                imp2Ftr: `bti${en1}${en2}i`,
                imp2P: `بت${ar1}${ar2}و`,
                imp2Ptr: `bti${en1}${en2}u`,
                imp3M: `ب${ar1}${ar2}ي`,
                imp3Mtr: `bi${en1}${en2}i`,
                imp3F: `بت${ar1}${ar2}ي`,
                imp3Ftr: `bti${en1}${en2}i`,
                imp3P: `ب${ar1}${ar2}و`,
                imp3Ptr: `bi${en1}${en2}u`,
                past1S: `${ar1}${ar2}يت`,
                past1Str: `${en1}${en2}īt`,
                past1P: `${ar1}${ar2}ينا`,
                past1Ptr: `${en1}${en2}īna`,
                past2F: `${ar1}${ar2}يتي`,
                past2Ftr: `${en1}${en2}īti`,
                past2P: `${ar1}${ar2}يتو`,
                past2Ptr: `${en1}${en2}ītu`,
                past3M: `${ar1}${ar2}ي`,
                past3Mtr: `${en1}i${en2}i`,
                past3F: `${ar1}${ar2}يت`,
                past3Ftr: `${en1}i${en2}yat`,
                past3P: `${ar1}${ar2}و`,
                past3Ptr: `${en1}i${en2}u`,
                amr2M: `إ${ar1}${ar2}ي`,
                amr2Mtr: `ʔi${en1}${en2}i`,
                amr2F: `إ${ar1}${ar2}ي`,
                amr2Ftr: `ʔi${en1}${en2}i`,
                amr2P: `إ${ar1}${ar2}و`,
                amr2Ptr: `ʔi${en1}${en2}u`,
            }),

            "ʔaža": () => ({
                imp1S: `با${ar2}ي`,
                imp1Str: `bā${en2}i`,
                imp1P: `مني${ar2}ي`,
                imp1Ptr: `mnī${en2}i`,
                imp2F: `بتي${ar2}ي`,
                imp2Ftr: `btī${en2}i`,
                imp2P: `بتي${ar2}و`,
                imp2Ptr: `btī${en2}u`,
                imp3M: `بي${ar2}ي`,
                imp3Mtr: `bī${en2}i`,
                imp3F: `بتي${ar2}ي`,
                imp3Ftr: `btī${en2}i`,
                imp3P: `بي${ar2}و`,
                imp3Ptr: `bī${en2}u`,
                past1S: `${ar2}يت`,
                past1Str: `${en2}īt`,
                past1P: `${ar2}ينا`,
                past1Ptr: `${en2}īna`,
                past2F: `${ar2}يتي`,
                past2Ftr: `${en2}īti`,
                past2P: `${ar2}يتو`,
                past2Ptr: `${en2}ītu`,
                past3M: `${ar1}${ar2}ى`,
                past3Mtr: `${en1}a${en2}a`,
                past3F: `${ar1}${ar2}ت`,
                past3Ftr: `${en1}a${en2}at`,
                past3P: `${ar1}${ar2}و`,
                past3Ptr: `${en1}a${en2}u`,
                amr2M: `تعال`,
                amr2Mtr: `taʕāl`,
                amr2F: `تعالي`,
                amr2Ftr: `taʕāli`,
                amr2P: `تعالو`,
                amr2Ptr: `taʕālu`,
            }),

            "Ci": () => ({
                imp1S: `ب${ar1}${ar2}ّ`,
                imp1Str: `ba${en1}i${en2}${en2}`,
                imp1P: `من${ar1}${ar2}ّ`,
                imp1Ptr: `min${en1}i${en2}${en2}`,
                imp2F: `بت${ar1}${ar2}ّي`,
                imp2Ftr: `bit${en1}i${en2}${en2}i`,
                imp2P: `بت${ar1}${ar2}ّو`,
                imp2Ptr: `bit${en1}i${en2}${en2}u`,
                imp3M: `ب${ar1}${ar2}ّ`,
                imp3Mtr: `bi${en1}i${en2}${en2}`,
                imp3F: `بت${ar1}${ar2}ّ`,
                imp3Ftr: `bit${en1}i${en2}${en2}`,
                imp3P: `ب${ar1}${ar2}ّو`,
                imp3Ptr: `bi${en1}i${en2}${en2}u`,
                past1S: `${ar1}${ar2}ّيت`,
                past1Str: `${en1}a${en2}${en2}ēt`,
                past1P: `${ar1}${ar2}ّينا`,
                past1Ptr: `${en1}a${en2}${en2}ēna`,
                past2F: `${ar1}${ar2}ّيتي`,
                past2Ftr: `${en1}a${en2}${en2}ēti`,
                past2P: `${ar1}${ar2}ّيتو`,
                past2Ptr: `${en1}a${en2}${en2}ētu`,
                past3M: `${ar1}${ar2}ّ`,
                past3Mtr: `${en1}a${en2}${en2}`,
                past3F: `${ar1}${ar2}ّت`,
                past3Ftr: `${en1}a${en2}${en2}at`,
                past3P: `${ar1}${ar2}ّو`,
                past3Ptr: `${en1}a${en2}${en2}u`,
                amr2M: `${ar1}${ar2}ّ`,
                amr2Mtr: `${en1}i${en2}${en2}`,
                amr2F: `${ar1}${ar2}ّي`,
                amr2Ftr: `${en1}i${en2}${en2}i`,
                amr2P: `${ar1}${ar2}ّو`,
                amr2Ptr: `${en1}i${en2}${en2}u`,
            }),

            "Cu": () => ({
                imp1S: `ب${ar1}${ar2}ّ`,
                imp1Str: `ba${en1}u${en2}${en2}`,
                imp1P: `من${ar1}${ar2}ّ`,
                imp1Ptr: `min${en1}u${en2}${en2}`,
                imp2F: `بت${ar1}${ar2}ّي`,
                imp2Ftr: `bit${en1}u${en2}${en2}i`,
                imp2P: `بت${ar1}${ar2}ّو`,
                imp2Ptr: `bit${en1}u${en2}${en2}u`,
                imp3M: `ب${ar1}${ar2}ّ`,
                imp3Mtr: `bi${en1}u${en2}${en2}`,
                imp3F: `بت${ar1}${ar2}ّ`,
                imp3Ftr: `bit${en1}u${en2}${en2}`,
                imp3P: `ب${ar1}${ar2}ّو`,
                imp3Ptr: `bi${en1}u${en2}${en2}u`,
                past1S: `${ar1}${ar2}ّيت`,
                past1Str: `${en1}a${en2}${en2}ēt`,
                past1P: `${ar1}${ar2}ّينا`,
                past1Ptr: `${en1}a${en2}${en2}ēna`,
                past2F: `${ar1}${ar2}ّيتي`,
                past2Ftr: `${en1}a${en2}${en2}ēti`,
                past2P: `${ar1}${ar2}ّيتو`,
                past2Ptr: `${en1}a${en2}${en2}ētu`,
                past3M: `${ar1}${ar2}ّ`,
                past3Mtr: `${en1}a${en2}${en2}`,
                past3F: `${ar1}${ar2}ّت`,
                past3Ftr: `${en1}a${en2}${en2}at`,
                past3P: `${ar1}${ar2}ّو`,
                past3Ptr: `${en1}a${en2}${en2}u`,
                amr2M: `${ar1}${ar2}ّ`,
                amr2Mtr: `${en1}u${en2}${en2}`,
                amr2F: `${ar1}${ar2}ّي`,
                amr2Ftr: `${en1}u${en2}${en2}i`,
                amr2P: `${ar1}${ar2}ّو`,
                amr2Ptr: `${en1}u${en2}${en2}u`,
            }),

            "Ca": () => ({
                imp1S: `ب${ar1}${ar2}ّ`,
                imp1Str: `ba${en1}a${en2}${en2}`,
                imp1P: `من${ar1}${ar2}ّ`,
                imp1Ptr: `min${en1}a${en2}${en2}`,
                imp2F: `بت${ar1}${ar2}ّي`,
                imp2Ftr: `bit${en1}a${en2}${en2}i`,
                imp2P: `بت${ar1}${ar2}ّو`,
                imp2Ptr: `bit${en1}a${en2}${en2}u`,
                imp3M: `ب${ar1}${ar2}ّ`,
                imp3Mtr: `bi${en1}a${en2}${en2}`,
                imp3F: `بت${ar1}${ar2}ّ`,
                imp3Ftr: `bit${en1}a${en2}${en2}`,
                imp3P: `ب${ar1}${ar2}ّو`,
                imp3Ptr: `bi${en1}a${en2}${en2}u`,
                past1S: `${ar1}${ar2}ّيت`,
                past1Str: `${en1}a${en2}${en2}ēt`,
                past1P: `${ar1}${ar2}ّينا`,
                past1Ptr: `${en1}a${en2}${en2}ēna`,
                past2F: `${ar1}${ar2}ّيتي`,
                past2Ftr: `${en1}a${en2}${en2}ēti`,
                past2P: `${ar1}${ar2}ّيتو`,
                past2Ptr: `${en1}a${en2}${en2}ētu`,
                past3M: `${ar1}${ar2}ّ`,
                past3Mtr: `${en1}a${en2}${en2}`,
                past3F: `${ar1}${ar2}ّت`,
                past3Ftr: `${en1}a${en2}${en2}at`,
                past3P: `${ar1}${ar2}ّو`,
                past3Ptr: `${en1}a${en2}${en2}u`,
                amr2M: `${ar1}${ar2}ّ`,
                amr2Mtr: `${en1}a${en2}${en2}`,
                amr2F: `${ar1}${ar2}ّي`,
                amr2Ftr: `${en1}a${en2}${en2}i`,
                amr2P: `${ar1}${ar2}ّو`,
                amr2Ptr: `${en1}a${en2}${en2}u`,
            }),

            "DY": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}ī${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `min${en1}ī${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bit${en1}ī${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bit${en1}ī${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bi${en1}ī${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `bit${en1}ī${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}ī${en3}u`,
                past1S: `${ar1}${ar3}ت`,
                past1Str: `${en1}i${en3}t`,
                past1P: `${ar1}${ar3}نا`,
                past1Ptr: `${en1}i${en3}na`,
                past2F: `${ar1}${ar3}تي`,
                past2Ftr: `${en1}i${en3}ti`,
                past2P: `${ar1}${ar3}تو`,
                past2Ptr: `${en1}i${en3}tu`,
                past3M: `${ar1}ا${ar3}`,
                past3Mtr: `${en1}ā${en3}`,
                past3F: `${ar1}ا${ar3}ت`,
                past3Ftr: `${en1}ā${en3}at`,
                past3P: `${ar1}ا${ar3}و`,
                past3Ptr: `${en1}ā${en3}u`,
                amr2M: `${ar1}${ar2}${ar3}`,
                amr2Mtr: `${en1}ī${en3}`,
                amr2F: `${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `${en1}ī${en3}i`,
                amr2P: `${ar1}${ar2}${ar3}و`,
                amr2Ptr: `${en1}ī${en3}u`,
            }),

            "DW": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}ū${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `min${en1}ū${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bit${en1}ū${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bit${en1}ū${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bi${en1}ū${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `bit${en1}ū${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}ū${en3}u`,
                past1S: `${ar1}${ar3}ت`,
                past1Str: `${en1}u${en3}t`,
                past1P: `${ar1}${ar3}نا`,
                past1Ptr: `${en1}u${en3}na`,
                past2F: `${ar1}${ar3}تي`,
                past2Ftr: `${en1}u${en3}ti`,
                past2P: `${ar1}${ar3}تو`,
                past2Ptr: `${en1}u${en3}tu`,
                past3M: `${ar1}ا${ar3}`,
                past3Mtr: `${en1}ā${en3}`,
                past3F: `${ar1}ا${ar3}ت`,
                past3Ftr: `${en1}ā${en3}at`,
                past3P: `${ar1}ا${ar3}و`,
                past3Ptr: `${en1}ā${en3}u`,
                amr2M: `${ar1}${ar2}${ar3}`,
                amr2Mtr: `${en1}ū${en3}`,
                amr2F: `${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `${en1}ū${en3}i`,
                amr2P: `${ar1}${ar2}${ar3}و`,
                amr2Ptr: `${en1}ū${en3}u`,
            }),

            "DAi": () => ({
                imp1S: `ب${ar1}ا${ar3}`,
                imp1Str: `ba${en1}ā${en3}`,
                imp1P: `من${ar1}ا${ar3}`,
                imp1Ptr: `min${en1}ā${en3}`,
                imp2F: `بت${ar1}ا${ar3}ي`,
                imp2Ftr: `bit${en1}ā${en3}i`,
                imp2P: `بت${ar1}ا${ar3}و`,
                imp2Ptr: `bit${en1}ā${en3}u`,
                imp3M: `ب${ar1}ا${ar3}`,
                imp3Mtr: `bi${en1}ā${en3}`,
                imp3F: `بت${ar1}ا${ar3}`,
                imp3Ftr: `bit${en1}ā${en3}`,
                imp3P: `ب${ar1}ا${ar3}و`,
                imp3Ptr: `bi${en1}ā${en3}u`,
                past1S: `${ar1}${ar3}ت`,
                past1Str: `${en1}i${en3}t`,
                past1P: `${ar1}${ar3}نا`,
                past1Ptr: `${en1}i${en3}na`,
                past2F: `${ar1}${ar3}تي`,
                past2Ftr: `${en1}i${en3}ti`,
                past2P: `${ar1}${ar3}تو`,
                past2Ptr: `${en1}i${en3}tu`,
                past3M: `${ar1}ا${ar3}`,
                past3Mtr: `${en1}ā${en3}`,
                past3F: `${ar1}ا${ar3}ت`,
                past3Ftr: `${en1}ā${en3}at`,
                past3P: `${ar1}ا${ar3}و`,
                past3Ptr: `${en1}ā${en3}u`,
                amr2M: `${ar1}ا${ar3}`,
                amr2Mtr: `${en1}ā${en3}`,
                amr2F: `${ar1}ا${ar3}ي`,
                amr2Ftr: `${en1}ā${en3}i`,
                amr2P: `${ar1}ا${ar3}و`,
                amr2Ptr: `${en1}ā${en3}u`,
            }),

            "DAu": () => ({
                imp1S: `ب${ar1}ا${ar3}`,
                imp1Str: `ba${en1}ā${en3}`,
                imp1P: `من${ar1}ا${ar3}`,
                imp1Ptr: `min${en1}ā${en3}`,
                imp2F: `بت${ar1}ا${ar3}ي`,
                imp2Ftr: `bit${en1}ā${en3}i`,
                imp2P: `بت${ar1}ا${ar3}و`,
                imp2Ptr: `bit${en1}ā${en3}u`,
                imp3M: `ب${ar1}ا${ar3}`,
                imp3Mtr: `bi${en1}ā${en3}`,
                imp3F: `بت${ar1}ا${ar3}`,
                imp3Ftr: `bit${en1}ā${en3}`,
                imp3P: `ب${ar1}ا${ar3}و`,
                imp3Ptr: `bi${en1}ā${en3}u`,
                past1S: `${ar1}${ar3}ت`,
                past1Str: `${en1}u${en3}t`,
                past1P: `${ar1}${ar3}نا`,
                past1Ptr: `${en1}u${en3}na`,
                past2F: `${ar1}${ar3}تي`,
                past2Ftr: `${en1}u${en3}ti`,
                past2P: `${ar1}${ar3}تو`,
                past2Ptr: `${en1}u${en3}tu`,
                past3M: `${ar1}ا${ar3}`,
                past3Mtr: `${en1}ā${en3}`,
                past3F: `${ar1}ا${ar3}ت`,
                past3Ftr: `${en1}ā${en3}at`,
                past3P: `${ar1}ا${ar3}و`,
                past3Ptr: `${en1}ā${en3}u`,
                amr2M: `${ar1}ا${ar3}`,
                amr2Mtr: `${en1}ā${en3}`,
                amr2F: `${ar1}ا${ar3}ي`,
                amr2Ftr: `${en1}ā${en3}i`,
                amr2P: `${ar1}ا${ar3}و`,
                amr2Ptr: `${en1}ā${en3}u`,
            }),
        },

        "2": {
            "A": () => ({
                imp1S: `ب${ar1}${ar2}ّ${ar3}`,
                imp1Str: `ba${en1}a${en2}${en2}i${en3}`,
                imp1P: `من${ar1}${ar2}ّ${ar3}`,
                imp1Ptr: `min${en1}a${en2}${en2}i${en3}`,
                imp2F: `بت${ar1}${ar2}ّ${ar3}ي`,
                imp2Ftr: `bit${en1}a${en2}${en2}${en3}i`,
                imp2P: `بت${ar1}${ar2}ّ${ar3}و`,
                imp2Ptr: `bit${en1}a${en2}${en2}${en3}u`,
                imp3M: `ب${ar1}${ar2}ّ${ar3}`,
                imp3Mtr: `bi${en1}a${en2}${en2}i${en3}`,
                imp3F: `بت${ar1}${ar2}ّ${ar3}`,
                imp3Ftr: `bit${en1}a${en2}${en2}i${en3}`,
                imp3P: `ب${ar1}${ar2}ّ${ar3}و`,
                imp3Ptr: `bi${en1}a${en2}${en2}${en3}u`,
                past1S: `${ar1}${ar2}ّ${ar3}ت`,
                past1Str: `${en1}a${en2}${en2}a${en3}t`,
                past1P: `${ar1}${ar2}ّ${ar3}نا`,
                past1Ptr: `${en1}a${en2}${en2}a${en3}na`,
                past2F: `${ar1}${ar2}ّ${ar3}تي`,
                past2Ftr: `${en1}a${en2}${en2}a${en3}ti`,
                past2P: `${ar1}${ar2}ّ${ar3}تو`,
                past2Ptr: `${en1}a${en2}${en2}a${en3}tu`,
                past3M: `${ar1}${ar2}ّ${ar3}`,
                past3Mtr: `${en1}a${en2}${en2}a${en3}`,
                past3F: `${ar1}${ar2}ّ${ar3}ت`,
                past3Ftr: `${en1}a${en2}${en2}a${en3}at`,
                past3P: `${ar1}${ar2}ّ${ar3}و`,
                past3Ptr: `${en1}a${en2}${en2}a${en3}u`,
                amr2M: `${ar1}${ar2}ّ${ar3}`,
                amr2Mtr: `${en1}a${en2}${en2}i${en3}`,
                amr2F: `${ar1}${ar2}ّ${ar3}ي`,
                amr2Ftr: `${en1}a${en2}${en2}${en3}i`,
                amr2P: `${ar1}${ar2}ّ${ar3}و`,
                amr2Ptr: `${en1}a${en2}${en2}${en3}u`,
            }),

            "B": () => ({
                imp1S: `ب${ar1}${ar2}ّي`,
                imp1Str: `ba${en1}a${en2}${en2}i`,
                imp1P: `من${ar1}${ar2}ّي`,
                imp1Ptr: `min${en1}a${en2}${en2}i`,
                imp2F: `بت${ar1}${ar2}ّي`,
                imp2Ftr: `bit${en1}a${en2}${en2}i`,
                imp2P: `بت${ar1}${ar2}ّو`,
                imp2Ptr: `bit${en1}a${en2}${en2}u`,
                imp3M: `ب${ar1}${ar2}ّي`,
                imp3Mtr: `bi${en1}a${en2}${en2}i`,
                imp3F: `بت${ar1}${ar2}ّي`,
                imp3Ftr: `bit${en1}a${en2}${en2}i`,
                imp3P: `ب${ar1}${ar2}ّو`,
                imp3Ptr: `bi${en1}a${en2}${en2}u`,
                past1S: `${ar1}${ar2}ّيت`,
                past1Str: `${en1}a${en2}${en2}ēt`,
                past1P: `${ar1}${ar2}ّينا`,
                past1Ptr: `${en1}a${en2}${en2}ēna`,
                past2F: `${ar1}${ar2}ّيتي`,
                past2Ftr: `${en1}a${en2}${en2}ēti`,
                past2P: `${ar1}${ar2}ّيتو`,
                past2Ptr: `${en1}a${en2}${en2}ētu`,
                past3M: `${ar1}${ar2}ّى`,
                past3Mtr: `${en1}a${en2}${en2}a`,
                past3F: `${ar1}${ar2}ّت`,
                past3Ftr: `${en1}a${en2}${en2}at`,
                past3P: `${ar1}${ar2}ّو`,
                past3Ptr: `${en1}a${en2}${en2}u`,
                amr2M: `${ar1}${ar2}ّي`,
                amr2Mtr: `${en1}a${en2}${en2}i`,
                amr2F: `${ar1}${ar2}ّي`,
                amr2Ftr: `${en1}a${en2}${en2}i`,
                amr2P: `${ar1}${ar2}ّو`,
                amr2Ptr: `${en1}a${en2}${en2}u`,
            }),
        },

        "2Q": {
            "A": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}${ar4}`,
                imp1Str: `ba${en1}a${en2}${en3}i${en4}`,
                imp1P: `من${ar1}${ar2}${ar3}${ar4}`,
                imp1Ptr: `min${en1}a${en2}${en3}i${en4}`,
                imp2F: `بت${ar1}${ar2}${ar3}${ar4}ي`,
                imp2Ftr: `bit${en1}a${en2}${en3}i${en4}i`,
                imp2P: `بت${ar1}${ar2}${ar3}${ar4}و`,
                imp2Ptr: `bit${en1}a${en2}${en3}i${en4}u`,
                imp3M: `ب${ar1}${ar2}${ar3}${ar4}`,
                imp3Mtr: `bi${en1}a${en2}${en3}i${en4}`,
                imp3F: `بت${ar1}${ar2}${ar3}${ar4}`,
                imp3Ftr: `bit${en1}a${en2}${en3}i${en4}`,
                imp3P: `ب${ar1}${ar2}${ar3}${ar4}و`,
                imp3Ptr: `bi${en1}a${en2}${en3}i${en4}u`,
                past1S: `${ar1}${ar2}${ar3}${ar4}ت`,
                past1Str: `${en1}a${en2}${en3}a${en4}t`,
                past1P: `${ar1}${ar2}${ar3}${ar4}نا`,
                past1Ptr: `${en1}a${en2}${en3}a${en4}na`,
                past2F: `${ar1}${ar2}${ar3}${ar4}تي`,
                past2Ftr: `${en1}a${en2}${en3}a${en4}ti`,
                past2P: `${ar1}${ar2}${ar3}${ar4}تو`,
                past2Ptr: `${en1}a${en2}${en3}a${en4}tu`,
                past3M: `${ar1}${ar2}${ar3}${ar4}`,
                past3Mtr: `${en1}a${en2}${en3}a${en4}`,
                past3F: `${ar1}${ar2}${ar3}${ar4}ت`,
                past3Ftr: `${en1}a${en2}${en3}a${en4}at`,
                past3P: `${ar1}${ar2}${ar3}${ar4}و`,
                past3Ptr: `${en1}a${en2}${en3}a${en4}u`,
                amr2M: `${ar1}${ar2}${ar3}${ar4}`,
                amr2Mtr: `${en1}a${en2}${en3}i${en4}`,
                amr2F: `${ar1}${ar2}${ar3}${ar4}ي`,
                amr2Ftr: `${en1}a${en2}${en3}i${en4}i`,
                amr2P: `${ar1}${ar2}${ar3}${ar4}و`,
                amr2Ptr: `${en1}a${en2}${en3}i${en4}u`,
            }),

            "B": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}ي`,
                imp1Str: `ba${en1}a${en2}${en3}i`,
                imp1P: `من${ar1}${ar2}${ar3}ي`,
                imp1Ptr: `min${en1}a${en2}${en3}i`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bit${en1}a${en2}${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bit${en1}a${en2}${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}ي`,
                imp3Mtr: `bi${en1}a${en2}${en3}i`,
                imp3F: `بت${ar1}${ar2}${ar3}ي`,
                imp3Ftr: `bit${en1}a${en2}${en3}i`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}a${en2}${en3}u`,
                past1S: `${ar1}${ar2}${ar3}يت`,
                past1Str: `${en1}a${en2}${en3}ēt`,
                past1P: `${ar1}${ar2}${ar3}ينا`,
                past1Ptr: `${en1}a${en2}${en3}ēna`,
                past2F: `${ar1}${ar2}${ar3}يتي`,
                past2Ftr: `${en1}a${en2}${en3}ēti`,
                past2P: `${ar1}${ar2}${ar3}يتو`,
                past2Ptr: `${en1}a${en2}${en3}ētu`,
                past3M: `${ar1}${ar2}${ar3}ى`,
                past3Mtr: `${en1}a${en2}${en3}a`,
                past3F: `${ar1}${ar2}${ar3}ت`,
                past3Ftr: `${en1}a${en2}${en3}at`,
                past3P: `${ar1}${ar2}${ar3}و`,
                past3Ptr: `${en1}a${en2}${en3}u`,
                amr2M: `${ar1}${ar2}${ar3}ي`,
                amr2Mtr: `${en1}a${en2}${en3}i`,
                amr2F: `${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `${en1}a${en2}${en3}i`,
                amr2P: `${ar1}${ar2}${ar3}و`,
                amr2Ptr: `${en1}a${en2}${en3}u`,
            }),
        },

        "3": {
            "A": () => ({
                imp1S: `ب${ar1}ا${ar2}${ar3}`,
                imp1Str: `ba${en1}ā${en2}i${en3}`,
                imp1P: `من${ar1}ا${ar2}${ar3}`,
                imp1Ptr: `min${en1}ā${en2}i${en3}`,
                imp2F: `بت${ar1}ا${ar2}${ar3}ي`,
                imp2Ftr: `bit${en1}ā${en2}${en3}i`,
                imp2P: `بت${ar1}ا${ar2}${ar3}و`,
                imp2Ptr: `bit${en1}ā${en2}${en3}u`,
                imp3M: `ب${ar1}ا${ar2}${ar3}`,
                imp3Mtr: `bi${en1}ā${en2}i${en3}`,
                imp3F: `بت${ar1}ا${ar2}${ar3}`,
                imp3Ftr: `bit${en1}ā${en2}i${en3}`,
                imp3P: `ب${ar1}ا${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}ā${en2}${en3}u`,
                past1S: `${ar1}ا${ar2}${ar3}ت`,
                past1Str: `${en1}ā${en2}a${en3}t`,
                past1P: `${ar1}ا${ar2}${ar3}نا`,
                past1Ptr: `${en1}ā${en2}a${en3}na`,
                past2F: `${ar1}ا${ar2}${ar3}تي`,
                past2Ftr: `${en1}ā${en2}a${en3}ti`,
                past2P: `${ar1}ا${ar2}${ar3}تو`,
                past2Ptr: `${en1}ā${en2}a${en3}tu`,
                past3M: `${ar1}ا${ar2}${ar3}`,
                past3Mtr: `${en1}ā${en2}a${en3}`,
                past3F: `${ar1}ا${ar2}${ar3}ت`,
                past3Ftr: `${en1}ā${en2}a${en3}at`,
                past3P: `${ar1}ا${ar2}${ar3}و`,
                past3Ptr: `${en1}ā${en2}a${en3}u`,
                amr2M: `${ar1}ا${ar2}${ar3}`,
                amr2Mtr: `${en1}ā${en2}i${en3}`,
                amr2F: `${ar1}ا${ar2}${ar3}ي`,
                amr2Ftr: `${en1}ā${en2}${en3}i`,
                amr2P: `${ar1}ا${ar2}${ar3}و`,
                amr2Ptr: `${en1}ā${en2}${en3}u`,
            }),

            "B": () => ({
                imp1S: `ب${ar1}ا${ar2}ي`,
                imp1Str: `ba${en1}ā${en2}i`,
                imp1P: `من${ar1}ا${ar2}ي`,
                imp1Ptr: `min${en1}ā${en2}i`,
                imp2F: `بت${ar1}ا${ar2}ي`,
                imp2Ftr: `bit${en1}ā${en2}i`,
                imp2P: `بت${ar1}ا${ar2}و`,
                imp2Ptr: `bit${en1}ā${en2}u`,
                imp3M: `ب${ar1}ا${ar2}ي`,
                imp3Mtr: `bi${en1}ā${en2}i`,
                imp3F: `بت${ar1}ا${ar2}ي`,
                imp3Ftr: `bit${en1}ā${en2}i`,
                imp3P: `ب${ar1}ا${ar2}و`,
                imp3Ptr: `bi${en1}ā${en2}u`,
                past1S: `${ar1}ا${ar2}يت`,
                past1Str: `${en1}ā${en2}ēt`,
                past1P: `${ar1}ا${ar2}ينا`,
                past1Ptr: `${en1}ā${en2}ēna`,
                past2F: `${ar1}ا${ar2}يتي`,
                past2Ftr: `${en1}ā${en2}ēti`,
                past2P: `${ar1}ا${ar2}يتو`,
                past2Ptr: `${en1}ā${en2}ētu`,
                past3M: `${ar1}ا${ar2}ى`,
                past3Mtr: `${en1}ā${en2}a`,
                past3F: `${ar1}ا${ar2}ت`,
                past3Ftr: `${en1}ā${en2}at`,
                past3P: `${ar1}ا${ar2}و`,
                past3Ptr: `${en1}ā${en2}u`,
                amr2M: `${ar1}ا${ar2}ي`,
                amr2Mtr: `${en1}ā${en2}i`,
                amr2F: `${ar1}ا${ar2}ي`,
                amr2Ftr: `${en1}ā${en2}i`,
                amr2P: `${ar1}ا${ar2}و`,
                amr2Ptr: `${en1}ā${en2}u`,
            }),
        },

        "4": {
            "A": () => ({
                imp1S: `بن${ar1}${ar2}${ar3}`,
                imp1Str: `bani${en1}${en2}i${en3}`,
                imp1P: `منن${ar1}${ar2}${ar3}`,
                imp1Ptr: `mnini${en1}${en2}i${en3}`,
                imp2F: `بتن${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `btin${en1}i${en2}${en3}i`,
                imp2P: `بتن${ar1}${ar2}${ar3}و`,
                imp2Ptr: `btin${en1}i${en2}${en3}u`,
                imp3M: `بن${ar1}${ar2}${ar3}`,
                imp3Mtr: `bini${en1}${en2}i${en3}`,
                imp3F: `بتن${ar1}${ar2}${ar3}`,
                imp3Ftr: `btini${en1}${en2}i${en3}`,
                imp3P: `بن${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bin${en1}i${en2}${en3}u`,
                past1S: `ان${ar1}${ar2}${ar3}ت`,
                past1Str: `in${en1}a${en2}a${en3}t`,
                past1P: `ان${ar1}${ar2}${ar3}نا`,
                past1Ptr: `in${en1}a${en2}a${en3}na`,
                past2F: `ان${ar1}${ar2}${ar3}تي`,
                past2Ftr: `in${en1}a${en2}a${en3}ti`,
                past2P: `ان${ar1}${ar2}${ar3}تو`,
                past2Ptr: `in${en1}a${en2}a${en3}tu`,
                past3M: `ان${ar1}${ar2}${ar3}`,
                past3Mtr: `in${en1}a${en2}a${en3}`,
                past3F: `ان${ar1}${ar2}${ar3}ت`,
                past3Ftr: `in${en1}a${en2}${en3}at`,
                past3P: `ان${ar1}${ar2}${ar3}و`,
                past3Ptr: `in${en1}a${en2}a${en3}u`,
                amr2M: `إن${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔin${en1}${en2}i${en3}`,
                amr2F: `إن${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔin${en1}i${en2}${en3}i`,
                amr2P: `إن${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔin${en1}i${en2}${en3}u`,
            }),

            "B": () => ({
                imp1S: `بن${ar1}${ar2}ي`,
                imp1Str: `bani${en1}${en2}i`,
                imp1P: `منن${ar1}${ar2}ي`,
                imp1Ptr: `mnini${en1}${en2}i`,
                imp2F: `بتن${ar1}${ar2}ي`,
                imp2Ftr: `btini${en1}${en2}i`,
                imp2P: `بتن${ar1}${ar2}و`,
                imp2Ptr: `btini${en1}${en2}u`,
                imp3M: `بن${ar1}${ar2}ي`,
                imp3Mtr: `bini${en1}${en2}i`,
                imp3F: `بتن${ar1}${ar2}ي`,
                imp3Ftr: `btini${en1}${en2}i`,
                imp3P: `بن${ar1}${ar2}و`,
                imp3Ptr: `bini${en1}${en2}u`,
                past1S: `ان${ar1}${ar2}يت`,
                past1Str: `in${en1}a${en2}ēt`,
                past1P: `ان${ar1}${ar2}ينا`,
                past1Ptr: `in${en1}a${en2}ēna`,
                past2F: `ان${ar1}${ar2}يتي`,
                past2Ftr: `in${en1}a${en2}ēti`,
                past2P: `ان${ar1}${ar2}يتو`,
                past2Ptr: `in${en1}a${en2}ētu`,
                past3M: `ان${ar1}${ar2}ى`,
                past3Mtr: `in${en1}a${en2}a`,
                past3F: `ان${ar1}${ar2}ت`,
                past3Ftr: `in${en1}a${en2}at`,
                past3P: `ان${ar1}${ar2}و`,
                past3Ptr: `in${en1}a${en2}u`,
                amr2M: `إن${ar1}${ar2}ي`,
                amr2Mtr: `ʔini${en1}${en2}i`,
                amr2F: `إن${ar1}${ar2}ي`,
                amr2Ftr: `ʔini${en1}${en2}i`,
                amr2P: `إن${ar1}${ar2}و`,
                amr2Ptr: `ʔini${en1}${en2}u`,
            }),

            "C": () => ({
                imp1S: `بن${ar1}${ar2}ّ`,
                imp1Str: `ban${en1}a${en2}${en2}`,
                imp1P: `منن${ar1}${ar2}ّ`,
                imp1Ptr: `mnin${en1}a${en2}${en2}`,
                imp2F: `بتن${ar1}${ar2}ّي`,
                imp2Ftr: `btin${en1}a${en2}${en2}i`,
                imp2P: `بتن${ar1}${ar2}ّو`,
                imp2Ptr: `btin${en1}a${en2}${en2}u`,
                imp3M: `بن${ar1}${ar2}ّ`,
                imp3Mtr: `bin${en1}a${en2}${en2}`,
                imp3F: `بتن${ar1}${ar2}ّ`,
                imp3Ftr: `btin${en1}a${en2}${en2}`,
                imp3P: `بن${ar1}${ar2}ّو`,
                imp3Ptr: `bin${en1}a${en2}${en2}u`,
                past1S: `ان${ar1}${ar2}ّيت`,
                past1Str: `in${en1}a${en2}${en2}ēt`,
                past1P: `ان${ar1}${ar2}ّينا`,
                past1Ptr: `in${en1}a${en2}${en2}ēna`,
                past2F: `ان${ar1}${ar2}ّيتي`,
                past2Ftr: `in${en1}a${en2}${en2}ēti`,
                past2P: `ان${ar1}${ar2}ّيتو`,
                past2Ptr: `in${en1}a${en2}${en2}ētu`,
                past3M: `ان${ar1}${ar2}ّ`,
                past3Mtr: `in${en1}a${en2}${en2}`,
                past3F: `ان${ar1}${ar2}ّت`,
                past3Ftr: `in${en1}a${en2}${en2}at`,
                past3P: `ان${ar1}${ar2}ّو`,
                past3Ptr: `in${en1}a${en2}${en2}u`,
                amr2M: `إن${ar1}${ar2}ّ`,
                amr2Mtr: `ʔin${en1}a${en2}${en2}`,
                amr2F: `إن${ar1}${ar2}ّي`,
                amr2Ftr: `ʔin${en1}a${en2}${en2}i`,
                amr2P: `إن${ar1}${ar2}ّو`,
                amr2Ptr: `ʔin${en1}a${en2}${en2}u`,
            }),

            "D": () => ({
            }),
        },

        "5": {
            "A": () => ({
                imp1S: `بت${ar1}${ar2}ّ${ar3}`,
                imp1Str: `bat${en1}a${en2}${en2}a${en3}`,
                imp1P: `منت${ar1}${ar2}ّ${ar3}`,
                imp1Ptr: `mnit${en1}a${en2}${en2}a${en3}`,
                imp2F: `بتت${ar1}${ar2}ّ${ar3}ي`,
                imp2Ftr: `btit${en1}a${en2}${en2}a${en3}i`,
                imp2P: `بتت${ar1}${ar2}ّ${ar3}و`,
                imp2Ptr: `btit${en1}a${en2}${en2}a${en3}u`,
                imp3M: `بت${ar1}${ar2}ّ${ar3}`,
                imp3Mtr: `bit${en1}a${en2}${en2}a${en3}`,
                imp3F: `بتت${ar1}${ar2}ّ${ar3}`,
                imp3Ftr: `btit${en1}a${en2}${en2}a${en3}`,
                imp3P: `بت${ar1}${ar2}ّ${ar3}و`,
                imp3Ptr: `bit${en1}a${en2}${en2}a${en3}u`,
                past1S: `ت${ar1}${ar2}ّ${ar3}ت`,
                past1Str: `t${en1}a${en2}${en2}a${en3}t`,
                past1P: `ت${ar1}${ar2}ّ${ar3}نا`,
                past1Ptr: `t${en1}a${en2}${en2}a${en3}na`,
                past2F: `ت${ar1}${ar2}ّ${ar3}تي`,
                past2Ftr: `t${en1}a${en2}${en2}a${en3}ti`,
                past2P: `ت${ar1}${ar2}ّ${ar3}تو`,
                past2Ptr: `t${en1}a${en2}${en2}a${en3}tu`,
                past3M: `ت${ar1}${ar2}ّ${ar3}`,
                past3Mtr: `t${en1}a${en2}${en2}a${en3}`,
                past3F: `ت${ar1}${ar2}ّ${ar3}ت`,
                past3Ftr: `t${en1}a${en2}${en2}a${en3}at`,
                past3P: `ت${ar1}${ar2}ّ${ar3}و`,
                past3Ptr: `t${en1}a${en2}${en2}a${en3}u`,
                amr2M: `ت${ar1}${ar2}ّ${ar3}`,
                amr2Mtr: `t${en1}a${en2}${en2}a${en3}`,
                amr2F: `ت${ar1}${ar2}ّ${ar3}ي`,
                amr2Ftr: `t${en1}a${en2}${en2}a${en3}i`,
                amr2P: `ت${ar1}${ar2}ّ${ar3}و`,
                amr2Ptr: `t${en1}a${en2}${en2}a${en3}u`,
            }),

            "B": () => ({
                imp1S: `بت${ar1}${ar2}ّى`,
                imp1Str: `bat${en1}a${en2}${en2}a`,
                imp1P: `منت${ar1}${ar2}ّى`,
                imp1Ptr: `mnit${en1}a${en2}${en2}a`,
                imp2F: `بتت${ar1}${ar2}ّي`,
                imp2Ftr: `btit${en1}a${en2}${en2}i`,
                imp2P: `بتت${ar1}${ar2}ّو`,
                imp2Ptr: `btit${en1}a${en2}${en2}u`,
                imp3M: `بت${ar1}${ar2}ّى`,
                imp3Mtr: `bit${en1}a${en2}${en2}a`,
                imp3F: `بتت${ar1}${ar2}ّى`,
                imp3Ftr: `btit${en1}a${en2}${en2}a`,
                imp3P: `بت${ar1}${ar2}ّو`,
                imp3Ptr: `bit${en1}a${en2}${en2}u`,
                past1S: `ت${ar1}${ar2}ّيت`,
                past1Str: `t${en1}a${en2}${en2}ēt`,
                past1P: `ت${ar1}${ar2}ّينا`,
                past1Ptr: `t${en1}a${en2}${en2}ēna`,
                past2F: `ت${ar1}${ar2}ّيتي`,
                past2Ftr: `t${en1}a${en2}${en2}ēti`,
                past2P: `ت${ar1}${ar2}ّيتو`,
                past2Ptr: `t${en1}a${en2}${en2}ētu`,
                past3M: `ت${ar1}${ar2}ّى`,
                past3Mtr: `t${en1}a${en2}${en2}a`,
                past3F: `ت${ar1}${ar2}ّت`,
                past3Ftr: `t${en1}a${en2}${en2}at`,
                past3P: `ت${ar1}${ar2}ّو`,
                past3Ptr: `t${en1}a${en2}${en2}u`,
                amr2M: `ت${ar1}${ar2}ّى`,
                amr2Mtr: `t${en1}a${en2}${en2}a`,
                amr2F: `ت${ar1}${ar2}ّي`,
                amr2Ftr: `t${en1}a${en2}${en2}i`,
                amr2P: `ت${ar1}${ar2}ّو`,
                amr2Ptr: `t${en1}a${en2}${en2}u`,
            }),
        },

        "5Q": {
            "A": () => ({
                imp1S: `بت${ar1}${ar2}${ar3}${ar4}`,
                imp1Str: `bat${en1}a${en2}${en3}a${en4}`,
                imp1P: `منت${ar1}${ar2}${ar3}${ar4}`,
                imp1Ptr: `mnit${en1}a${en2}${en3}a${en4}`,
                imp2F: `بتت${ar1}${ar2}${ar3}${ar4}ي`,
                imp2Ftr: `btit${en1}a${en2}${en3}a${en4}i`,
                imp2P: `بتت${ar1}${ar2}${ar3}${ar4}و`,
                imp2Ptr: `btit${en1}a${en2}${en3}a${en4}u`,
                imp3M: `بت${ar1}${ar2}${ar3}${ar4}`,
                imp3Mtr: `bit${en1}a${en2}${en3}a${en4}`,
                imp3F: `بتت${ar1}${ar2}${ar3}${ar4}`,
                imp3Ftr: `btit${en1}a${en2}${en3}a${en4}`,
                imp3P: `بت${ar1}${ar2}${ar3}${ar4}و`,
                imp3Ptr: `bit${en1}a${en2}${en3}a${en4}u`,
                past1S: `ت${ar1}${ar2}${ar3}${ar4}ت`,
                past1Str: `t${en1}a${en2}${en3}a${en4}t`,
                past1P: `ت${ar1}${ar2}${ar3}${ar4}نا`,
                past1Ptr: `t${en1}a${en2}${en3}a${en4}na`,
                past2F: `ت${ar1}${ar2}${ar3}${ar4}تي`,
                past2Ftr: `t${en1}a${en2}${en3}a${en4}ti`,
                past2P: `ت${ar1}${ar2}${ar3}${ar4}تو`,
                past2Ptr: `t${en1}a${en2}${en3}a${en4}tu`,
                past3M: `ت${ar1}${ar2}${ar3}${ar4}`,
                past3Mtr: `t${en1}a${en2}${en3}a${en4}`,
                past3F: `ت${ar1}${ar2}${ar3}${ar4}ت`,
                past3Ftr: `t${en1}a${en2}${en3}a${en4}at`,
                past3P: `ت${ar1}${ar2}${ar3}${ar4}و`,
                past3Ptr: `t${en1}a${en2}${en3}a${en4}u`,
                amr2M: `ت${ar1}${ar2}${ar3}${ar4}`,
                amr2Mtr: `t${en1}a${en2}${en3}a${en4}`,
                amr2F: `ت${ar1}${ar2}${ar3}${ar4}ي`,
                amr2Ftr: `t${en1}a${en2}${en3}a${en4}i`,
                amr2P: `ت${ar1}${ar2}${ar3}${ar4}و`,
                amr2Ptr: `t${en1}a${en2}${en3}a${en4}u`,
            }),

            "B": () => ({
            }),
        },

        "6": {
            "A": () => ({
                imp1S: `بت${ar1}ا${ar2}${ar3}`,
                imp1Str: `bat${en1}ā${en2}a${en3}`,
                imp1P: `منت${ar1}ا${ar2}${ar3}`,
                imp1Ptr: `mnit${en1}ā${en2}a${en3}`,
                imp2F: `بتت${ar1}ا${ar2}${ar3}ي`,
                imp2Ftr: `btit${en1}ā${en2}a${en3}i`,
                imp2P: `بتت${ar1}ا${ar2}${ar3}و`,
                imp2Ptr: `btit${en1}ā${en2}a${en3}u`,
                imp3M: `بت${ar1}ا${ar2}${ar3}`,
                imp3Mtr: `bit${en1}ā${en2}a${en3}`,
                imp3F: `بتت${ar1}ا${ar2}${ar3}`,
                imp3Ftr: `btit${en1}ā${en2}a${en3}`,
                imp3P: `بت${ar1}ا${ar2}${ar3}و`,
                imp3Ptr: `bit${en1}ā${en2}a${en3}u`,
                past1S: `ت${ar1}ا${ar2}${ar3}ت`,
                past1Str: `t${en1}ā${en2}a${en3}t`,
                past1P: `ت${ar1}ا${ar2}${ar3}نا`,
                past1Ptr: `t${en1}ā${en2}a${en3}na`,
                past2F: `ت${ar1}ا${ar2}${ar3}تي`,
                past2Ftr: `t${en1}ā${en2}a${en3}ti`,
                past2P: `ت${ar1}ا${ar2}${ar3}تو`,
                past2Ptr: `t${en1}ā${en2}a${en3}tu`,
                past3M: `ت${ar1}ا${ar2}${ar3}`,
                past3Mtr: `t${en1}ā${en2}a${en3}`,
                past3F: `ت${ar1}ا${ar2}${ar3}ت`,
                past3Ftr: `t${en1}ā${en2}a${en3}at`,
                past3P: `ت${ar1}ا${ar2}${ar3}و`,
                past3Ptr: `t${en1}ā${en2}a${en3}u`,
                amr2M: `ت${ar1}ا${ar2}${ar3}`,
                amr2Mtr: `t${en1}ā${en2}a${en3}`,
                amr2F: `ت${ar1}ا${ar2}${ar3}ي`,
                amr2Ftr: `t${en1}ā${en2}a${en3}i`,
                amr2P: `ت${ar1}ا${ar2}${ar3}و`,
                amr2Ptr: `t${en1}ā${en2}a${en3}u`,
            }),

            "B": () => ({
                imp1S: `بت${ar1}ا${ar2}ى`,
                imp1Str: `bat${en1}ā${en2}a`,
                imp1P: `منت${ar1}ا${ar2}ى`,
                imp1Ptr: `mnit${en1}ā${en2}a`,
                imp2F: `بتت${ar1}ا${ar2}ي`,
                imp2Ftr: `btit${en1}ā${en2}i`,
                imp2P: `بتت${ar1}ا${ar2}و`,
                imp2Ptr: `btit${en1}ā${en2}u`,
                imp3M: `بت${ar1}ا${ar2}ى`,
                imp3Mtr: `bit${en1}ā${en2}a`,
                imp3F: `بتت${ar1}ا${ar2}ى`,
                imp3Ftr: `btit${en1}ā${en2}a`,
                imp3P: `بت${ar1}ا${ar2}و`,
                imp3Ptr: `bit${en1}ā${en2}u`,
                past1S: `ت${ar1}ا${ar2}يت`,
                past1Str: `t${en1}ā${en2}ēt`,
                past1P: `ت${ar1}ا${ar2}ينا`,
                past1Ptr: `t${en1}ā${en2}ēna`,
                past2F: `ت${ar1}ا${ar2}يتي`,
                past2Ftr: `t${en1}ā${en2}ēti`,
                past2P: `ت${ar1}ا${ar2}يتو`,
                past2Ptr: `t${en1}ā${en2}ētu`,
                past3M: `ت${ar1}ا${ar2}ى`,
                past3Mtr: `t${en1}ā${en2}a`,
                past3F: `ت${ar1}ا${ar2}ت`,
                past3Ftr: `t${en1}ā${en2}at`,
                past3P: `ت${ar1}ا${ar2}و`,
                past3Ptr: `t${en1}ā${en2}u`,
                amr2M: `ت${ar1}ا${ar2}ى`,
                amr2Mtr: `t${en1}ā${en2}a`,
                amr2F: `ت${ar1}ا${ar2}ي`,
                amr2Ftr: `t${en1}ā${en2}i`,
                amr2P: `ت${ar1}ا${ar2}و`,
                amr2Ptr: `t${en1}ā${en2}u`,
            }),
        },

        "7": {
            "A": () => ({
                imp1S: `بست${ar1}${ar2}${ar3}`,
                imp1Str: `basta${en1}${en2}i${en3}`,
                imp1P: `منست${ar1}${ar2}${ar3}`,
                imp1Ptr: `mnista${en1}${en2}i${en3}`,
                imp2F: `بتست${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `btista${en1}${en2}i${en3}i`,
                imp2P: `بتست${ar1}${ar2}${ar3}و`,
                imp2Ptr: `btista${en1}${en2}i${en3}u`,
                imp3M: `بست${ar1}${ar2}${ar3}`,
                imp3Mtr: `bista${en1}${en2}i${en3}`,
                imp3F: `بتست${ar1}${ar2}${ar3}`,
                imp3Ftr: `btista${en1}${en2}i${en3}`,
                imp3P: `بست${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bista${en1}${en2}i${en3}u`,
                past1S: `است${ar1}${ar2}${ar3}ت`,
                past1Str: `ista${en1}${en2}a${en3}t`,
                past1P: `است${ar1}${ar2}${ar3}نا`,
                past1Ptr: `ista${en1}${en2}a${en3}na`,
                past2F: `است${ar1}${ar2}${ar3}تي`,
                past2Ftr: `ista${en1}${en2}a${en3}ti`,
                past2P: `است${ar1}${ar2}${ar3}تو`,
                past2Ptr: `ista${en1}${en2}a${en3}tu`,
                past3M: `است${ar1}${ar2}${ar3}`,
                past3Mtr: `ista${en1}${en2}a${en3}`,
                past3F: `است${ar1}${ar2}${ar3}ت`,
                past3Ftr: `ista${en1}${en2}${en3}at`,
                past3P: `است${ar1}${ar2}${ar3}و`,
                past3Ptr: `ista${en1}${en2}a${en3}u`,
                amr2M: `إست${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔista${en1}${en2}i${en3}`,
                amr2F: `إست${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔista${en1}${en2}i${en3}i`,
                amr2P: `إست${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔista${en1}${en2}i${en3}u`,
            }),

            "B": () => ({
                imp1S: `بست${ar1}${ar2}ي`,
                imp1Str: `basta${en1}${en2}i`,
                imp1P: `منست${ar1}${ar2}ي`,
                imp1Ptr: `mnista${en1}${en2}i`,
                imp2F: `بتست${ar1}${ar2}ي`,
                imp2Ftr: `btista${en1}${en2}i`,
                imp2P: `بتست${ar1}${ar2}و`,
                imp2Ptr: `btista${en1}${en2}u`,
                imp3M: `بست${ar1}${ar2}ي`,
                imp3Mtr: `bista${en1}${en2}i`,
                imp3F: `بتست${ar1}${ar2}ي`,
                imp3Ftr: `btista${en1}${en2}i`,
                imp3P: `بست${ar1}${ar2}و`,
                imp3Ptr: `bista${en1}${en2}u`,
                past1S: `است${ar1}${ar2}يت`,
                past1Str: `ista${en1}${en2}ēt`,
                past1P: `است${ar1}${ar2}ينا`,
                past1Ptr: `ista${en1}${en2}ēna`,
                past2F: `است${ar1}${ar2}يتي`,
                past2Ftr: `ista${en1}${en2}ēti`,
                past2P: `است${ar1}${ar2}يتو`,
                past2Ptr: `ista${en1}${en2}ētu`,
                past3M: `است${ar1}${ar2}ى`,
                past3Mtr: `ista${en1}${en2}a`,
                past3F: `است${ar1}${ar2}ت`,
                past3Ftr: `ista${en1}${en2}at`,
                past3P: `است${ar1}${ar2}و`,
                past3Ptr: `ista${en1}${en2}u`,
                amr2M: `إست${ar1}${ar2}ي`,
                amr2Mtr: `ʔista${en1}${en2}i`,
                amr2F: `إست${ar1}${ar2}ي`,
                amr2Ftr: `ʔista${en1}${en2}i`,
                amr2P: `إست${ar1}${ar2}و`,
                amr2Ptr: `ʔista${en1}${en2}u`,
            }),

            "C": () => ({
                imp1S: `بست${ar1}${ar2}ّ`,
                imp1Str: `basta${en1}i${en2}${en2}`,
                imp1P: `منست${ar1}${ar2}ّ`,
                imp1Ptr: `mnista${en1}i${en2}${en2}`,
                imp2F: `بتست${ar1}${ar2}ّي`,
                imp2Ftr: `btista${en1}i${en2}${en2}i`,
                imp2P: `بتست${ar1}${ar2}ّو`,
                imp2Ptr: `btista${en1}i${en2}${en2}u`,
                imp3M: `بست${ar1}${ar2}ّ`,
                imp3Mtr: `bista${en1}i${en2}${en2}`,
                imp3F: `بتست${ar1}${ar2}ّ`,
                imp3Ftr: `btista${en1}i${en2}${en2}`,
                imp3P: `بست${ar1}${ar2}ّو`,
                imp3Ptr: `bista${en1}i${en2}${en2}u`,
                past1S: `است${ar1}${ar2}ّيت`,
                past1Str: `ista${en1}a${en2}${en2}ēt`,
                past1P: `است${ar1}${ar2}ّينا`,
                past1Ptr: `ista${en1}a${en2}${en2}ēna`,
                past2F: `است${ar1}${ar2}ّيتي`,
                past2Ftr: `ista${en1}a${en2}${en2}ēti`,
                past2P: `است${ar1}${ar2}ّيتو`,
                past2Ptr: `ista${en1}a${en2}${en2}ētu`,
                past3M: `است${ar1}${ar2}ّ`,
                past3Mtr: `ista${en1}a${en2}${en2}`,
                past3F: `است${ar1}${ar2}ّت`,
                past3Ftr: `ista${en1}a${en2}${en2}at`,
                past3P: `است${ar1}${ar2}ّو`,
                past3Ptr: `ista${en1}a${en2}${en2}u`,
                amr2M: `إست${ar1}${ar2}ّ`,
                amr2Mtr: `ʔista${en1}i${en2}${en2}`,
                amr2F: `إست${ar1}${ar2}ّي`,
                amr2Ftr: `ʔista${en1}i${en2}${en2}i`,
                amr2P: `إست${ar1}${ar2}ّو`,
                amr2Ptr: `ʔista${en1}i${en2}${en2}u`,
            }),

            "D": () => ({
                imp1S: `بست${ar1}${ar2}${ar3}`,
                imp1Str: `basta${en1}ī${en3}`,
                imp1P: `منست${ar1}${ar2}${ar3}`,
                imp1Ptr: `mnista${en1}ī${en3}`,
                imp2F: `بتست${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `btista${en1}ī${en3}i`,
                imp2P: `بتست${ar1}${ar2}${ar3}و`,
                imp2Ptr: `btista${en1}ī${en3}u`,
                imp3M: `بست${ar1}${ar2}${ar3}`,
                imp3Mtr: `bista${en1}ī${en3}`,
                imp3F: `بتست${ar1}${ar2}${ar3}`,
                imp3Ftr: `btista${en1}ī${en3}`,
                imp3P: `بست${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bista${en1}ī${en3}u`,
                past1S: `است${ar1}${ar3}ت`,
                past1Str: `ista${en1}a${en3}t`,
                past1P: `است${ar1}${ar3}نا`,
                past1Ptr: `ista${en1}a${en3}na`,
                past2F: `است${ar1}${ar3}تي`,
                past2Ftr: `ista${en1}a${en3}ti`,
                past2P: `است${ar1}${ar3}تو`,
                past2Ptr: `ista${en1}a${en3}tu`,
                past3M: `است${ar1}ا${ar3}`,
                past3Mtr: `ista${en1}ā${en3}`,
                past3F: `است${ar1}ا${ar3}ت`,
                past3Ftr: `ista${en1}ā${en3}at`,
                past3P: `است${ar1}ا${ar3}و`,
                past3Ptr: `ista${en1}ā${en3}u`,
                amr2M: `إست${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔista${en1}ī${en3}`,
                amr2F: `إست${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔista${en1}ī${en3}i`,
                amr2P: `إست${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔista${en1}ī${en3}u`,
            }),

            "istanna": () => ({
                imp1S: `بست${ar1}${ar2}ى`,
                imp1Str: `basta${en1}${en2}a`,
                imp1P: `منست${ar1}${ar2}ى`,
                imp1Ptr: `mnista${en1}${en2}a`,
                imp2F: `بتست${ar1}${ar2}ي`,
                imp2Ftr: `btista${en1}${en2}i`,
                imp2P: `بتست${ar1}${ar2}و`,
                imp2Ptr: `btista${en1}${en2}u`,
                imp3M: `بست${ar1}${ar2}ى`,
                imp3Mtr: `bista${en1}${en2}a`,
                imp3F: `بتست${ar1}${ar2}ى`,
                imp3Ftr: `btista${en1}${en2}a`,
                imp3P: `بست${ar1}${ar2}و`,
                imp3Ptr: `bista${en1}${en2}u`,
                past1S: `است${ar1}${ar2}يت`,
                past1Str: `ista${en1}${en2}ēt`,
                past1P: `است${ar1}${ar2}ينا`,
                past1Ptr: `ista${en1}${en2}ēna`,
                past2F: `است${ar1}${ar2}يتي`,
                past2Ftr: `ista${en1}${en2}ēti`,
                past2P: `است${ar1}${ar2}يتو`,
                past2Ptr: `ista${en1}${en2}ētu`,
                past3M: `است${ar1}${ar2}ى`,
                past3Mtr: `ista${en1}${en2}a`,
                past3F: `است${ar1}${ar2}ت`,
                past3Ftr: `ista${en1}${en2}at`,
                past3P: `است${ar1}${ar2}و`,
                past3Ptr: `ista${en1}${en2}u`,
                amr2M: `إست${ar1}${ar2}ى`,
                amr2Mtr: `ʔista${en1}${en2}a`,
                amr2F: `إست${ar1}${ar2}ي`,
                amr2Ftr: `ʔista${en1}${en2}i`,
                amr2P: `إست${ar1}${ar2}و`,
                amr2Ptr: `ʔista${en1}${en2}u`,
            }),
        },

        "8": {
            "A": () => ({
                imp1S: `ب${ar1}ت${ar2}${ar3}`,
                imp1Str: `ba${en1}t${en2}i${en3}`,
                imp1P: `من${ar1}ت${ar2}${ar3}`,
                imp1Ptr: `mni${en1}t${en2}i${en3}`,
                imp2F: `بت${ar1}ت${ar2}${ar3}ي`,
                imp2Ftr: `bti${en1}ti${en2}${en3}i`,
                imp2P: `بت${ar1}ت${ar2}${ar3}و`,
                imp2Ptr: `bti${en1}ti${en2}${en3}u`,
                imp3M: `ب${ar1}ت${ar2}${ar3}`,
                imp3Mtr: `bi${en1}t${en2}i${en3}`,
                imp3F: `بت${ar1}ت${ar2}${ar3}`,
                imp3Ftr: `bti${en1}t${en2}i${en3}`,
                imp3P: `ب${ar1}ت${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}ti${en2}${en3}u`,
                past1S: `ا${ar1}ت${ar2}${ar3}ت`,
                past1Str: `i${en1}ta${en2}a${en3}t`,
                past1P: `ا${ar1}ت${ar2}${ar3}نا`,
                past1Ptr: `i${en1}ta${en2}a${en3}na`,
                past2F: `ا${ar1}ت${ar2}${ar3}تي`,
                past2Ftr: `i${en1}ta${en2}a${en3}ti`,
                past2P: `ا${ar1}ت${ar2}${ar3}تو`,
                past2Ptr: `i${en1}ta${en2}a${en3}tu`,
                past3M: `ا${ar1}ت${ar2}${ar3}`,
                past3Mtr: `i${en1}ta${en2}a${en3}`,
                past3F: `ا${ar1}ت${ar2}${ar3}ت`,
                past3Ftr: `i${en1}ta${en2}${en3}at`,
                past3P: `ا${ar1}ت${ar2}${ar3}و`,
                past3Ptr: `i${en1}ta${en2}a${en3}u`,
                amr2M: `إ${ar1}ت${ar2}${ar3}`,
                amr2Mtr: `ʔi${en1}t${en2}i${en3}`,
                amr2F: `إ${ar1}ت${ar2}${ar3}ي`,
                amr2Ftr: `ʔi${en1}ti${en2}${en3}i`,
                amr2P: `إ${ar1}ت${ar2}${ar3}و`,
                amr2Ptr: `ʔi${en1}ti${en2}${en3}u`,
            }),

            "B": () => ({
                imp1S: `ب${ar1}ت${ar2}ي`,
                imp1Str: `ba${en1}t${en2}i`,
                imp1P: `من${ar1}ت${ar2}ي`,
                imp1Ptr: `mni${en1}t${en2}i`,
                imp2F: `بت${ar1}ت${ar2}ي`,
                imp2Ftr: `bti${en1}t${en2}i`,
                imp2P: `بت${ar1}ت${ar2}و`,
                imp2Ptr: `bti${en1}t${en2}u`,
                imp3M: `ب${ar1}ت${ar2}ي`,
                imp3Mtr: `bi${en1}t${en2}i`,
                imp3F: `بت${ar1}ت${ar2}ي`,
                imp3Ftr: `bti${en1}t${en2}i`,
                imp3P: `ب${ar1}ت${ar2}و`,
                imp3Ptr: `bi${en1}t${en2}u`,
                past1S: `ا${ar1}ت${ar2}يت`,
                past1Str: `i${en1}ta${en2}ēt`,
                past1P: `ا${ar1}ت${ar2}ينا`,
                past1Ptr: `i${en1}ta${en2}ēna`,
                past2F: `ا${ar1}ت${ar2}يتي`,
                past2Ftr: `i${en1}ta${en2}ēti`,
                past2P: `ا${ar1}ت${ar2}يتو`,
                past2Ptr: `i${en1}ta${en2}ētu`,
                past3M: `ا${ar1}ت${ar2}ى`,
                past3Mtr: `i${en1}ta${en2}a`,
                past3F: `ا${ar1}ت${ar2}ت`,
                past3Ftr: `i${en1}ta${en2}at`,
                past3P: `ا${ar1}ت${ar2}و`,
                past3Ptr: `i${en1}ta${en2}u`,
                amr2M: `إ${ar1}ت${ar2}ي`,
                amr2Mtr: `ʔi${en1}t${en2}i`,
                amr2F: `إ${ar1}ت${ar2}ي`,
                amr2Ftr: `ʔi${en1}t${en2}i`,
                amr2P: `إ${ar1}ت${ar2}و`,
                amr2Ptr: `ʔi${en1}t${en2}u`,
            }),

            "C": () => ({
                imp1S: `ب${ar1}ت${ar2}ّ`,
                imp1Str: `ba${en1}ta${en2}${en2}`,
                imp1P: `من${ar1}ت${ar2}ّ`,
                imp1Ptr: `mni${en1}ta${en2}${en2}`,
                imp2F: `بت${ar1}ت${ar2}ّي`,
                imp2Ftr: `bti${en1}ta${en2}${en2}i`,
                imp2P: `بت${ar1}ت${ar2}ّو`,
                imp2Ptr: `bti${en1}ta${en2}${en2}u`,
                imp3M: `ب${ar1}ت${ar2}ّ`,
                imp3Mtr: `bi${en1}ta${en2}${en2}`,
                imp3F: `بت${ar1}ت${ar2}ّ`,
                imp3Ftr: `bti${en1}ta${en2}${en2}`,
                imp3P: `ب${ar1}ت${ar2}ّو`,
                imp3Ptr: `bi${en1}ta${en2}${en2}u`,
                past1S: `ا${ar1}ت${ar2}ّيت`,
                past1Str: `i${en1}ta${en2}${en2}ēt`,
                past1P: `ا${ar1}ت${ar2}ّينا`,
                past1Ptr: `i${en1}ta${en2}${en2}ēna`,
                past2F: `ا${ar1}ت${ar2}ّيتي`,
                past2Ftr: `i${en1}ta${en2}${en2}ēti`,
                past2P: `ا${ar1}ت${ar2}ّيتو`,
                past2Ptr: `i${en1}ta${en2}${en2}ētu`,
                past3M: `ا${ar1}ت${ar2}ّ`,
                past3Mtr: `i${en1}ta${en2}${en2}`,
                past3F: `ا${ar1}ت${ar2}ّت`,
                past3Ftr: `i${en1}ta${en2}${en2}at`,
                past3P: `ا${ar1}ت${ar2}ّو`,
                past3Ptr: `i${en1}ta${en2}${en2}u`,
                amr2M: `إ${ar1}ت${ar2}ّ`,
                amr2Mtr: `ʔi${en1}ta${en2}${en2}`,
                amr2F: `إ${ar1}ت${ar2}ّي`,
                amr2Ftr: `ʔi${en1}ta${en2}${en2}i`,
                amr2P: `إ${ar1}ت${ar2}ّو`,
                amr2Ptr: `ʔi${en1}ta${en2}${en2}u`,
            }),

            "D": () => ({
                imp1S: `ب${ar1}تا${ar3}`,
                imp1Str: `ba${en1}tā${en3}`,
                imp1P: `من${ar1}تا${ar3}`,
                imp1Ptr: `mni${en1}tā${en3}`,
                imp2F: `بت${ar1}تا${ar3}ي`,
                imp2Ftr: `bti${en1}tā${en3}i`,
                imp2P: `بت${ar1}تا${ar3}و`,
                imp2Ptr: `bti${en1}tā${en3}u`,
                imp3M: `ب${ar1}تا${ar3}`,
                imp3Mtr: `bi${en1}tā${en3}`,
                imp3F: `بت${ar1}تا${ar3}`,
                imp3Ftr: `bti${en1}tā${en3}`,
                imp3P: `ب${ar1}تا${ar3}و`,
                imp3Ptr: `bi${en1}tā${en3}u`,
                past1S: `ا${ar1}ت${ar3}ت`,
                past1Str: `i${en1}ta${en3}t`,
                past1P: `ا${ar1}ت${ar3}نا`,
                past1Ptr: `i${en1}ta${en3}na`,
                past2F: `ا${ar1}ت${ar3}تي`,
                past2Ftr: `i${en1}ta${en3}ti`,
                past2P: `ا${ar1}ت${ar3}تو`,
                past2Ptr: `i${en1}ta${en3}tu`,
                past3M: `ا${ar1}تا${ar3}`,
                past3Mtr: `i${en1}tā${en3}`,
                past3F: `ا${ar1}تا${ar3}ت`,
                past3Ftr: `i${en1}tā${en3}at`,
                past3P: `ا${ar1}تا${ar3}و`,
                past3Ptr: `i${en1}tā${en3}u`,
                amr2M: `إ${ar1}تا${ar3}`,
                amr2Mtr: `ʔi${en1}tā${en3}`,
                amr2F: `إ${ar1}تا${ar3}ي`,
                amr2Ftr: `ʔi${en1}tā${en3}i`,
                amr2P: `إ${ar1}تا${ar3}و`,
                amr2Ptr: `ʔi${en1}tā${en3}u`,
            }),

            "E": () => ({
                imp1S: `بتّ${ar2}${ar3}`,
                imp1Str: `batt${en2}i${en3}`,
                imp1P: `منتّ${ar2}${ar3}`,
                imp1Ptr: `mnitt${en2}i${en3}`,
                imp2F: `بتتّ${ar2}${ar3}ي`,
                imp2Ftr: `btitti${en2}${en3}i`,
                imp2P: `بتتّ${ar2}${ar3}و`,
                imp2Ptr: `btitti${en2}${en3}u`,
                imp3M: `بتّ${ar2}${ar3}`,
                imp3Mtr: `bitt${en2}i${en3}`,
                imp3F: `بتتّ${ar2}${ar3}`,
                imp3Ftr: `btitt${en2}i${en3}`,
                imp3P: `بتّ${ar2}${ar3}و`,
                imp3Ptr: `bitti${en2}${en3}u`,
                past1S: `اتّ${ar2}${ar3}ت`,
                past1Str: `itta${en2}a${en3}t`,
                past1P: `اتّ${ar2}${ar3}نا`,
                past1Ptr: `itta${en2}a${en3}na`,
                past2F: `اتّ${ar2}${ar3}تي`,
                past2Ftr: `itta${en2}a${en3}ti`,
                past2P: `اتّ${ar2}${ar3}تو`,
                past2Ptr: `itta${en2}a${en3}tu`,
                past3M: `اتّ${ar2}${ar3}`,
                past3Mtr: `itta${en2}a${en3}`,
                past3F: `اتّ${ar2}${ar3}ت`,
                past3Ftr: `itta${en2}${en3}at`,
                past3P: `اتّ${ar2}${ar3}و`,
                past3Ptr: `itta${en2}a${en3}u`,
                amr2M: `إتّ${ar2}${ar3}`,
                amr2Mtr: `ʔitt${en2}i${en3}`,
                amr2F: `إتّ${ar2}${ar3}ي`,
                amr2Ftr: `ʔitti${en2}${en3}i`,
                amr2P: `إتّ${ar2}${ar3}و`,
                amr2Ptr: `ʔitti${en2}${en3}u`,
            }),
        },

        "9": {
            "A": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}ّ`,
                imp1Str: `ba${en1}${en2}a${en3}${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}ّ`,
                imp1Ptr: `mni${en1}${en2}a${en3}${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ّي`,
                imp2Ftr: `bti${en1}${en2}a${en3}${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}ّو`,
                imp2Ptr: `bti${en1}${en2}a${en3}${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}ّ`,
                imp3Mtr: `bi${en1}${en2}a${en3}${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}ّ`,
                imp3Ftr: `bti${en1}${en2}a${en3}${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}ّو`,
                imp3Ptr: `bi${en1}${en2}a${en3}${en3}u`,
                past1S: `ا${ar1}${ar2}${ar3}ّيت`,
                past1Str: `i${en1}${en2}a${en3}${en3}ēt`,
                past1P: `ا${ar1}${ar2}${ar3}ّينا`,
                past1Ptr: `i${en1}${en2}a${en3}${en3}ēna`,
                past2F: `ا${ar1}${ar2}${ar3}ّيتي`,
                past2Ftr: `i${en1}${en2}a${en3}${en3}ēti`,
                past2P: `ا${ar1}${ar2}${ar3}ّيتو`,
                past2Ptr: `i${en1}${en2}a${en3}${en3}ētu`,
                past3M: `ا${ar1}${ar2}${ar3}ّ`,
                past3Mtr: `i${en1}${en2}a${en3}${en3}`,
                past3F: `ا${ar1}${ar2}${ar3}ّت`,
                past3Ftr: `i${en1}${en2}a${en3}${en3}at`,
                past3P: `ا${ar1}${ar2}${ar3}ّو`,
                past3Ptr: `i${en1}${en2}a${en3}${en3}u`,
                amr2M: `إ${ar1}${ar2}${ar3}ّ`,
                amr2Mtr: `ʔi${en1}${en2}a${en3}${en3}`,
                amr2F: `إ${ar1}${ar2}${ar3}ّي`,
                amr2Ftr: `ʔi${en1}${en2}a${en3}${en3}i`,
                amr2P: `إ${ar1}${ar2}${ar3}ّو`,
                amr2Ptr: `ʔi${en1}${en2}a${en3}${en3}u`,
            }),
        },

        "X": {
            "A": () => ({
                imp1S: `ب${ar1}${ar2}${ar3}`,
                imp1Str: `ba${en1}${en2}i${en3}`,
                imp1P: `من${ar1}${ar2}${ar3}`,
                imp1Ptr: `mni${en1}${en2}i${en3}`,
                imp2F: `بت${ar1}${ar2}${ar3}ي`,
                imp2Ftr: `bti${en1}${en2}i${en3}i`,
                imp2P: `بت${ar1}${ar2}${ar3}و`,
                imp2Ptr: `bti${en1}${en2}i${en3}u`,
                imp3M: `ب${ar1}${ar2}${ar3}`,
                imp3Mtr: `bi${en1}${en2}i${en3}`,
                imp3F: `بت${ar1}${ar2}${ar3}`,
                imp3Ftr: `bti${en1}${en2}i${en3}`,
                imp3P: `ب${ar1}${ar2}${ar3}و`,
                imp3Ptr: `bi${en1}${en2}i${en3}u`,
                past1S: `أ${ar1}${ar2}${ar3}ت`,
                past1Str: `ʔa${en1}${en2}a${en3}t`,
                past1P: `أ${ar1}${ar2}${ar3}نا`,
                past1Ptr: `ʔa${en1}${en2}a${en3}na`,
                past2F: `أ${ar1}${ar2}${ar3}تي`,
                past2Ftr: `ʔa${en1}${en2}a${en3}ti`,
                past2P: `أ${ar1}${ar2}${ar3}تو`,
                past2Ptr: `ʔa${en1}${en2}a${en3}tu`,
                past3M: `أ${ar1}${ar2}${ar3}`,
                past3Mtr: `ʔa${en1}${en2}a${en3}`,
                past3F: `أ${ar1}${ar2}${ar3}ت`,
                past3Ftr: `ʔa${en1}${en2}${en3}at`,
                past3P: `أ${ar1}${ar2}${ar3}و`,
                past3Ptr: `ʔa${en1}${en2}a${en3}u`,
                amr2M: `إ${ar1}${ar2}${ar3}`,
                amr2Mtr: `ʔi${en1}${en2}i${en3}`,
                amr2F: `إ${ar1}${ar2}${ar3}ي`,
                amr2Ftr: `ʔi${en1}${en2}i${en3}i`,
                amr2P: `إ${ar1}${ar2}${ar3}و`,
                amr2Ptr: `ʔi${en1}${en2}i${en3}u`,
            }),

            "B": () => ({
                imp1S: `ب${ar1}${ar2}ي`,
                imp1Str: `ba${en1}${en2}i`,
                imp1P: `من${ar1}${ar2}ي`,
                imp1Ptr: `mni${en1}${en2}i`,
                imp2F: `بت${ar1}${ar2}ي`,
                imp2Ftr: `bti${en1}${en2}i`,
                imp2P: `بت${ar1}${ar2}و`,
                imp2Ptr: `bti${en1}${en2}u`,
                imp3M: `ب${ar1}${ar2}ي`,
                imp3Mtr: `bi${en1}${en2}i`,
                imp3F: `بت${ar1}${ar2}ي`,
                imp3Ftr: `bti${en1}${en2}i`,
                imp3P: `ب${ar1}${ar2}و`,
                imp3Ptr: `bi${en1}${en2}u`,
                past1S: `أ${ar1}${ar2}يت`,
                past1Str: `ʔa${en1}${en2}ēt`,
                past1P: `أ${ar1}${ar2}ينا`,
                past1Ptr: `ʔa${en1}${en2}ēna`,
                past2F: `أ${ar1}${ar2}يتي`,
                past2Ftr: `ʔa${en1}${en2}ēti`,
                past2P: `أ${ar1}${ar2}يتو`,
                past2Ptr: `ʔa${en1}${en2}ētu`,
                past3M: `أ${ar1}${ar2}ى`,
                past3Mtr: `ʔa${en1}${en2}a`,
                past3F: `أ${ar1}${ar2}ت`,
                past3Ftr: `ʔa${en1}${en2}at`,
                past3P: `أ${ar1}${ar2}و`,
                past3Ptr: `ʔa${en1}${en2}u`,
                amr2M: `إ${ar1}${ar2}ي`,
                amr2Mtr: `ʔi${en1}${en2}i`,
                amr2F: `إ${ar1}${ar2}ي`,
                amr2Ftr: `ʔi${en1}${en2}i`,
                amr2P: `إ${ar1}${ar2}و`,
                amr2Ptr: `ʔi${en1}${en2}u`,
            }),

            "C": () => ({
                imp1S: `ب${ar1}${ar2}ّ`,
                imp1Str: `ba${en1}i${en2}${en2}`,
                imp1P: `من${ar1}${ar2}ّ`,
                imp1Ptr: `min${en1}i${en2}${en2}`,
                imp2F: `بت${ar1}${ar2}ّي`,
                imp2Ftr: `bit${en1}i${en2}${en2}i`,
                imp2P: `بت${ar1}${ar2}ّو`,
                imp2Ptr: `bit${en1}i${en2}${en2}u`,
                imp3M: `ب${ar1}${ar2}ّ`,
                imp3Mtr: `bi${en1}i${en2}${en2}`,
                imp3F: `بت${ar1}${ar2}ّ`,
                imp3Ftr: `bit${en1}i${en2}${en2}`,
                imp3P: `ب${ar1}${ar2}ّو`,
                imp3Ptr: `bi${en1}i${en2}${en2}u`,
                past1S: `أ${ar1}${ar2}ّيت`,
                past1Str: `ʔa${en1}a${en2}${en2}ēt`,
                past1P: `أ${ar1}${ar2}ّينا`,
                past1Ptr: `ʔa${en1}a${en2}${en2}ēna`,
                past2F: `أ${ar1}${ar2}ّيتي`,
                past2Ftr: `ʔa${en1}a${en2}${en2}ēti`,
                past2P: `أ${ar1}${ar2}ّيتو`,
                past2Ptr: `ʔa${en1}a${en2}${en2}ētu`,
                past3M: `أ${ar1}${ar2}ّ`,
                past3Mtr: `ʔa${en1}a${en2}${en2}`,
                past3F: `أ${ar1}${ar2}ّت`,
                past3Ftr: `ʔa${en1}a${en2}${en2}at`,
                past3P: `أ${ar1}${ar2}ّو`,
                past3Ptr: `ʔa${en1}a${en2}${en2}u`,
                amr2M: `إ${ar1}${ar2}ّ`,
                amr2Mtr: `ʔi${en1}i${en2}${en2}`,
                amr2F: `إ${ar1}${ar2}ّي`,
                amr2Ftr: `ʔi${en1}i${en2}${en2}i`,
                amr2P: `إ${ar1}${ar2}ّو`,
                amr2Ptr: `ʔi${en1}i${en2}${en2}u`,
            }),

            "D": () => ({
            }),
        },
    }

    let conjugationResult;

    const formCases = forms[pattern.form];
    if (!formCases) return {};

    const conjugations = formCases[pattern.pattern];
    if (!conjugations) return {};

    conjugationResult = conjugations();

    for (const key in conjugationResult) {
        if (typeof conjugationResult[key] === 'string') {
            conjugationResult[key] = conjugationResult[key].replace(/أا/g, 'آ');
        }
    }

    if (['و', 'ي'].includes(ar1) && ['A1', 'A2i', 'A1a', 'A2'].includes(pattern.pattern)) {
        const fieldsToProcess = [
            'imp1Ptr', 'imp2Ftr', 'imp2Ptr', 'imp3Mtr', 'imp3Ftr', 'imp3Ptr',
            'amr2Mtr', 'amr2Ftr', 'amr2Ptr'
        ];

        for (const field of fieldsToProcess) {
            if (typeof conjugationResult[field] === 'string') {
                conjugationResult[field] = conjugationResult[field].replace(/iw/g, 'ū');
                conjugationResult[field] = conjugationResult[field].replace(/iy/g, 'ī');
            }
        }
    }

    return conjugationResult;
}
